import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
const code=fs.readFileSync(new URL('../src/app/mass-labels.js',import.meta.url),'utf8');
function setup(ubuntu=false){
 const ops=[],rp={modules:{},status:{fonts:{}}};let creates=0;
 const ctx={font:'',measureText(text){const factor=ubuntu&&this.font.includes('Ubuntu')?1.1:1;return{width:text.length*48*factor,actualBoundingBoxLeft:0,actualBoundingBoxRight:text.length*48*factor,actualBoundingBoxAscent:67,actualBoundingBoxDescent:1};},save(){},beginPath(){},rect(...a){ops.push(['clipRect',...a]);},clip(){},restore(){},strokeText(...a){ops.push(['stroke',...a,this.strokeStyle,this.lineWidth,this.font]);},fillText(...a){ops.push(['fill',...a,this.fillStyle,this.font]);}};
 const canvas={getContext:()=>ctx};const document={createElement(tag){assert.equal(tag,'canvas');creates++;return canvas;}};
 vm.runInNewContext(code,{window:{RYUTEN_PORT:rp},document});return{api:rp.modules.massLabels,ops,rp,canvas,creates:()=>creates};
}
test('All ten digits have a black outline before an opaque white fill',()=>{const t=setup();t.api.createAtlas();const ops=t.ops.filter(x=>x[0]!=='clipRect');assert.equal(ops.length,20);for(let n=0;n<10;n++){assert.deepEqual(ops[n*2].slice(0,2),['stroke',String(n)]);assert.equal(ops[n*2][4],'#000000');assert.equal(ops[n*2][5],12);assert.equal(ops[n*2+1][4],'#ffffff');}});
test('A single 512px atlas is cached; no per-frame canvas work',()=>{const t=setup(),c=t.api.createAtlas(),count=t.ops.length;for(let i=0;i<100;i++)assert.equal(t.api.createAtlas(),c);assert.equal(t.creates(),1);assert.equal(t.ops.length,count);assert.equal(c.width,512);assert.equal(c.height,512);});
test('Available local Ubuntu is selected without downloading a font',()=>{const t=setup(true);t.api.createAtlas();assert.equal(t.api.snapshot().localUbuntuAvailable,true);assert.match(t.api.snapshot().family,/Ubuntu/);assert.equal(t.api.snapshot().runtimeFontRequests,0);});
test('Missing Ubuntu uses a declared local sans-serif fallback, not an invented exact match',()=>{const t=setup();t.api.createAtlas();assert.equal(t.api.snapshot().localUbuntuAvailable,false);assert.equal(t.api.snapshot().family,'Arial, sans-serif');assert.equal(t.api.snapshot().exactNativeBitmap,false);});
test('Digit texture slots retain the native atlas coordinates',()=>{const t=setup();assert.equal(t.api.rects.length,10);assert.deepEqual([...t.api.rects[1]],[346,290,72,105]);for(const[x,y,w,h]of t.api.rects){assert.ok(x>=0&&y>=0&&x+w<=512&&y+h<=512);}});
test('Mass style never alters name colors, gameplay objects or native settings',()=>{const t=setup();t.rp.nameTint=()=>0xffff00;t.api.createAtlas();assert.equal(t.rp.nameTint(),0xffff00);assert.equal(t.api.snapshot().inheritedNameTint,false);assert.ok(!('host'in t.rp));});
test('Generated script contains the guarded white mass seam and preserves name tint',()=>{const s=fs.readFileSync(new URL('../dist/RYUTEN-Senpa.user.js',import.meta.url),'utf8');const match=s.indexOf('const PAYLOAD=')+'const PAYLOAD='.length;const payload=JSON.parse(s.slice(match,s.indexOf('\nfor(const [key,canonical]',match)).replace(/;\s*$/,''));assert.ok(payload.ryutenJS.includes('e.children.forEach(s=>s.tint=0xffffff)'));assert.ok(payload.ryutenJS.includes('i.tint=globalThis.RYUTEN_PORT.nameTint(t)'));assert.ok(!payload.ryutenJS.includes('e.children.forEach(s=>s.tint=globalThis.RYUTEN_PORT.nameTint(t))'));});
test('Recovered baseline reconstructs byte-for-byte',async()=>{const {execFileSync}=await import('node:child_process');const output=execFileSync(process.execPath,['build.mjs','--baseline'],{cwd:new URL('..',import.meta.url),encoding:'utf8'});assert.match(output,/byte-identically/);});
